Updated Princeton student links
hackprinceton/static pull request #13
Opened 2017-10-13 02:50 UTC by dfan97

This is ready to merge once the localhost ui is updated to fall and the dates on the hosting application are changed from spring to fall.

2017-10-15 00:56 UTC, casey-chow approved these changes

2017-10-15 00:58 UTC, zacharyliu commented on princeton.html
> +            <p>Sign up at <a href="https://goo.gl/forms/P6GEb5QPNe834b373">this form</a>.</p>
point to `/host` instead, and update the redirect for that page

2017-10-15 00:58 UTC, zacharyliu commented on travel.html
> +            <p>Please park in the North Garage (<a href="https://goo.gl/maps/grzxysUX2jG2">map</a>), located near Friend Center at the northeast corner of campus. If the garage is full, you may also
should make it more obvious that this is *not* the same as previous years since Lot 21 was almost always the lot we used

2017-10-15 01:15 UTC, casey-chow requested changes

2017-10-15 01:15 UTC, casey-chow commented on travel.html
> +            <p>Please park in the North Garage (<a href="https://goo.gl/maps/grzxysUX2jG2">map</a>), located near Friend Center at the northeast corner of campus. If the garage is full, you may also
Bold the `not`, add links to Ivy Lane and Lot 2.

2017-10-16 00:48 UTC, casey-chow approved these changes

2017-10-16 00:48 UTC, merged